// frontend-next/components/settings/tenant-orgs.tsx
"use client";

import { useCallback, useEffect, useState } from "react";
import { Modal } from "@/components/modal";
import { IconEdit, IconPlus, IconRefresh, IconTrash } from "@/components/icons";
import { Select } from "@/components/select";
import {
  listOrgs,
  createOrg,
  updateOrg,
  deleteOrg,
  listOrgMembers,
  addOrgMember,
  updateOrgMemberRole,
  removeOrgMember,
  createOrgInviteLink,
  fetchAllTenantMembers,
  type TenantOrg,
  type TenantOrgMember,
  type TenantOrgRole,
  type TenantMember,
  type TenantRole,
} from "@/lib/api/tenants";
import { useAuth } from "@/lib/auth";
import { copyToClipboard } from "@/lib/clipboard";

export function TenantOrgs() {
  const auth = useAuth();
  const activeTenantId = Number(auth.selectedTenantId ?? auth.tenant?.id ?? 0);
  const currentRole =
    auth.memberships.find((m) => String(m.tenant_id) === String(activeTenantId))?.role ?? "";
  const isSystemAdmin = auth.user?.is_system_admin === true;
  const canManageTenant = currentRole === "owner" || currentRole === "admin" || isSystemAdmin;

  const [orgs, setOrgs] = useState<TenantOrg[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");

  // Create / Edit Org Modal
  const [orgModalOpen, setOrgModalOpen] = useState(false);
  const [editingOrg, setEditingOrg] = useState<TenantOrg | null>(null);
  const [orgName, setOrgName] = useState("");
  const [orgDesc, setOrgDesc] = useState("");
  const [savingOrg, setSavingOrg] = useState(false);

  // Delete Org Confirmation
  const [deletingOrg, setDeletingOrg] = useState<TenantOrg | null>(null);
  const [deletingBusy, setDeletingBusy] = useState(false);

  // Org Members Modal
  const [activeOrg, setActiveOrg] = useState<TenantOrg | null>(null);
  const [members, setMembers] = useState<TenantOrgMember[]>([]);
  const [allTenantMembers, setAllTenantMembers] = useState<TenantMember[]>([]);
  const [loadingMembers, setLoadingMembers] = useState(false);
  const [newMemberUserId, setNewMemberUserId] = useState("");
  const [newMemberRole, setNewMemberRole] = useState<TenantOrgRole>("member");
  const [addingMember, setAddingMember] = useState(false);

  // Invite Link Modal
  const [inviteOrg, setInviteOrg] = useState<TenantOrg | null>(null);
  const [inviteRole, setInviteRole] = useState<TenantRole>("member");
  const [inviteMsg, setInviteMsg] = useState("");
  const [inviteUrl, setInviteUrl] = useState("");
  const [linkCopied, setLinkCopied] = useState(false);
  const [generatingLink, setGeneratingLink] = useState(false);

  const loadOrgs = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      const res = await listOrgs();
      if (res.success && res.data) {
        setOrgs(res.data);
      } else {
        setError(res.message || "Failed to load organizations");
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to load organizations");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    void loadOrgs();
  }, [loadOrgs]);

  // Open Create Modal
  const openCreate = () => {
    setEditingOrg(null);
    setOrgName("");
    setOrgDesc("");
    setOrgModalOpen(true);
  };

  // Open Edit Modal
  const openEdit = (org: TenantOrg) => {
    setEditingOrg(org);
    setOrgName(org.name);
    setOrgDesc(org.description || "");
    setOrgModalOpen(true);
  };

  // Save Org
  const handleSaveOrg = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!orgName.trim()) return;
    setSavingOrg(true);
    setError("");
    try {
      if (editingOrg) {
        const res = await updateOrg(editingOrg.id, {
          name: orgName.trim(),
          description: orgDesc.trim() || undefined,
        });
        if (res.success) {
          setSuccess(`Updated organization ${orgName}`);
          setOrgModalOpen(false);
          await loadOrgs();
        } else {
          setError(res.message || "Failed to update organization");
        }
      } else {
        const res = await createOrg({
          name: orgName.trim(),
          description: orgDesc.trim() || undefined,
        });
        if (res.success) {
          setSuccess(`Created organization ${orgName}`);
          setOrgModalOpen(false);
          await loadOrgs();
        } else {
          setError(res.message || "Failed to create organization");
        }
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to save organization");
    } finally {
      setSavingOrg(false);
    }
  };

  // Delete Org
  const handleDeleteOrg = async () => {
    if (!deletingOrg) return;
    setDeletingBusy(true);
    setError("");
    try {
      const res = await deleteOrg(deletingOrg.id);
      if (res.success) {
        setSuccess(`Deleted organization ${deletingOrg.name}`);
        setDeletingOrg(null);
        await loadOrgs();
      } else {
        setError(res.message || "Failed to delete organization");
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to delete organization");
    } finally {
      setDeletingBusy(false);
    }
  };

  // Open Members Modal
  const openMembersModal = async (org: TenantOrg) => {
    setActiveOrg(org);
    setLoadingMembers(true);
    setNewMemberUserId("");
    setNewMemberRole("member");
    try {
      const [mRes, tmRes] = await Promise.all([
        listOrgMembers(org.id),
        activeTenantId ? fetchAllTenantMembers(activeTenantId) : Promise.resolve([]),
      ]);
      if (mRes.success && mRes.data) {
        setMembers(mRes.data);
      }
      setAllTenantMembers(tmRes);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to load org members");
    } finally {
      setLoadingMembers(false);
    }
  };

  // Add Member to Org
  const handleAddMember = async () => {
    if (!activeOrg || !newMemberUserId) return;
    setAddingMember(true);
    setError("");
    try {
      const res = await addOrgMember(activeOrg.id, {
        user_id: newMemberUserId,
        role: newMemberRole,
      });
      if (res.success) {
        setNewMemberUserId("");
        const refreshed = await listOrgMembers(activeOrg.id);
        if (refreshed.success && refreshed.data) setMembers(refreshed.data);
        await loadOrgs();
      } else {
        setError(res.message || "Failed to add member to organization");
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to add member");
    } finally {
      setAddingMember(false);
    }
  };

  // Update Org Member Role
  const handleToggleMemberRole = async (member: TenantOrgMember) => {
    if (!activeOrg) return;
    const nextRole: TenantOrgRole = member.role === "manager" ? "member" : "manager";
    try {
      const res = await updateOrgMemberRole(activeOrg.id, member.user_id, { role: nextRole });
      if (res.success) {
        const refreshed = await listOrgMembers(activeOrg.id);
        if (refreshed.success && refreshed.data) setMembers(refreshed.data);
      } else {
        setError(res.message || "Failed to update role");
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to update role");
    }
  };

  // Remove Member from Org
  const handleRemoveMember = async (userId: string) => {
    if (!activeOrg) return;
    try {
      const res = await removeOrgMember(activeOrg.id, userId);
      if (res.success) {
        const refreshed = await listOrgMembers(activeOrg.id);
        if (refreshed.success && refreshed.data) setMembers(refreshed.data);
        await loadOrgs();
      } else {
        setError(res.message || "Failed to remove member");
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to remove member");
    }
  };

  // Open Invite Link Modal
  const openInviteModal = (org: TenantOrg) => {
    setInviteOrg(org);
    setInviteRole("member");
    setInviteMsg("");
    setInviteUrl("");
    setLinkCopied(false);
  };

  // Generate Org Invite Link
  const handleGenerateOrgInvite = async () => {
    if (!inviteOrg) return;
    setGeneratingLink(true);
    setError("");
    try {
      const res = await createOrgInviteLink(inviteOrg.id, {
        role: inviteRole,
        message: inviteMsg.trim() || undefined,
      });
      if (res.success && res.data?.url) {
        const full = new URL(res.data.url, window.location.origin).toString();
        setInviteUrl(full);
      } else {
        setError(res.message || "Failed to generate invite link");
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to generate invite link");
    } finally {
      setGeneratingLink(false);
    }
  };

  // Candidates for org members: tenant members not yet in this org
  const memberCandidates = allTenantMembers.filter(
    (tm) => !members.some((om) => om.user_id === tm.user_id),
  );

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-hairline pb-5">
        <div>
          <h2 className="title-md font-semibold text-ink">Organizations</h2>
          <p className="caption text-muted mt-1">
            Group members into organizations to manage access to sensitive knowledge bases.
          </p>
        </div>

        <div className="flex items-center gap-2">
          {canManageTenant && (
            <button
              type="button"
              onClick={openCreate}
              className="btn btn-primary btn-sm flex items-center gap-1.5"
            >
              <IconPlus className="h-3.5 w-3.5" />
              <span>Create organization</span>
            </button>
          )}
          <button
            type="button"
            onClick={() => void loadOrgs()}
            className="btn btn-outline btn-sm flex items-center gap-1.5"
            title="Refresh organizations"
          >
            <IconRefresh className="h-3.5 w-3.5" />
          </button>
        </div>
      </div>

      {error && (
        <div className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700 dark:border-rose-900/50 dark:bg-rose-950/30 dark:text-rose-400">
          {error}
        </div>
      )}
      {success && (
        <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700 dark:border-emerald-900/50 dark:bg-emerald-950/30 dark:text-emerald-400">
          {success}
        </div>
      )}

      {/* Orgs Table */}
      <div className="overflow-hidden rounded-xl border border-hairline">
        <table className="w-full text-left border-collapse text-sm">
          <thead>
            <tr className="border-b border-hairline bg-surface-strong/50 text-xs font-semibold text-muted">
              <th className="py-3 px-4">Name</th>
              <th className="py-3 px-4">Description</th>
              <th className="py-3 px-4">Members</th>
              <th className="py-3 px-4">Created</th>
              <th className="py-3 px-4 text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-hairline">
            {loading ? (
              <tr>
                <td colSpan={5} className="py-12 text-center text-muted">
                  Loading organizations…
                </td>
              </tr>
            ) : orgs.length === 0 ? (
              <tr>
                <td colSpan={5} className="py-12 text-center text-muted">
                  No organizations found. Create one to organize members and access.
                </td>
              </tr>
            ) : (
              orgs.map((org) => (
                <tr key={org.id} className="hover:bg-surface-strong/30 transition-colors">
                  <td className="py-3.5 px-4 font-medium text-ink">
                    {org.name}
                  </td>
                  <td className="py-3.5 px-4 text-muted text-xs max-w-xs truncate">
                    {org.description || "—"}
                  </td>
                  <td className="py-3.5 px-4">
                    <button
                      type="button"
                      onClick={() => void openMembersModal(org)}
                      className="badge-pill hover:bg-surface-strong transition-colors"
                    >
                      {org.member_count || 0} members
                    </button>
                  </td>
                  <td className="py-3.5 px-4 text-muted text-xs">
                    {org.created_at ? new Date(org.created_at).toLocaleDateString() : "—"}
                  </td>
                  <td className="py-3.5 px-4 text-right space-x-1">
                    <button
                      type="button"
                      onClick={() => void openMembersModal(org)}
                      className="btn btn-outline btn-sm text-xs py-1"
                    >
                      Members
                    </button>
                    <button
                      type="button"
                      onClick={() => openInviteModal(org)}
                      className="btn btn-outline btn-sm text-xs py-1"
                    >
                      Invite
                    </button>
                    {canManageTenant && (
                      <>
                        <button
                          type="button"
                          onClick={() => openEdit(org)}
                          className="btn btn-ghost btn-sm p-1.5 text-muted hover:text-ink"
                          title="Edit"
                        >
                          <IconEdit className="h-3.5 w-3.5" />
                        </button>
                        <button
                          type="button"
                          onClick={() => setDeletingOrg(org)}
                          className="btn btn-ghost btn-sm p-1.5 text-muted hover:text-rose-600"
                          title="Delete"
                        >
                          <IconTrash className="h-3.5 w-3.5" />
                        </button>
                      </>
                    )}
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {/* Create / Edit Org Modal */}
      <Modal
        open={orgModalOpen}
        title={editingOrg ? "Edit Organization" : "Create Organization"}
        onClose={() => setOrgModalOpen(false)}
      >
        <form onSubmit={handleSaveOrg} className="space-y-4">
          <label className="block">
            <span className="caption mb-1.5 block text-muted">Organization Name</span>
            <input
              type="text"
              required
              placeholder="e.g. Core Engineering"
              className="input"
              value={orgName}
              onChange={(e) => setOrgName(e.target.value)}
            />
          </label>

          <label className="block">
            <span className="caption mb-1.5 block text-muted">Description (optional)</span>
            <textarea
              rows={3}
              placeholder="Brief summary of this group's responsibility"
              className="input resize-none"
              value={orgDesc}
              onChange={(e) => setOrgDesc(e.target.value)}
            />
          </label>

          <div className="flex justify-end gap-3 pt-3">
            <button
              type="button"
              className="btn btn-outline"
              onClick={() => setOrgModalOpen(false)}
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={savingOrg || !orgName.trim()}
              className="btn btn-primary"
            >
              {savingOrg ? "Saving…" : editingOrg ? "Save changes" : "Create organization"}
            </button>
          </div>
        </form>
      </Modal>

      {/* Delete Org Confirmation Modal */}
      <Modal
        open={deletingOrg !== null}
        title="Delete Organization"
        onClose={() => setDeletingOrg(null)}
      >
        <div className="space-y-4">
          <p className="body-sm text-body">
            Are you sure you want to delete <strong>{deletingOrg?.name}</strong>? Any knowledge
            bases restricted specifically to this organization will become inaccessible to its
            members.
          </p>
          <div className="flex justify-end gap-3 pt-2">
            <button
              type="button"
              className="btn btn-outline"
              onClick={() => setDeletingOrg(null)}
            >
              Cancel
            </button>
            <button
              type="button"
              disabled={deletingBusy}
              onClick={() => void handleDeleteOrg()}
              className="btn btn-primary bg-rose-600 hover:bg-rose-700 text-white"
            >
              {deletingBusy ? "Deleting…" : "Delete organization"}
            </button>
          </div>
        </div>
      </Modal>

      {/* Org Members Modal */}
      <Modal
        open={activeOrg !== null}
        title={`Members of ${activeOrg?.name || "Organization"}`}
        onClose={() => setActiveOrg(null)}
      >
        <div className="space-y-6">
          {/* Add member section */}
          {canManageTenant && (
            <div className="rounded-xl border border-hairline bg-surface-strong/30 p-4 space-y-3">
              <span className="caption font-medium text-ink">Add Member from Workspace</span>
              <div className="flex flex-wrap items-center gap-2">
                <Select
                  className="h-9 flex-1 min-w-[180px] text-sm"
                  value={newMemberUserId}
                  onChange={setNewMemberUserId}
                  placeholder="Select workspace member…"
                  options={memberCandidates.map((tm) => ({
                    value: tm.user_id,
                    label: `${tm.username || tm.email} (${tm.role})`,
                  }))}
                />
                <Select
                  className="h-9 w-32 text-sm"
                  value={newMemberRole}
                  onChange={(v) => setNewMemberRole(v as TenantOrgRole)}
                  options={[
                    { value: "member", label: "Member" },
                    { value: "manager", label: "Manager" },
                  ]}
                />
                <button
                  type="button"
                  disabled={addingMember || !newMemberUserId}
                  onClick={() => void handleAddMember()}
                  className="btn btn-primary btn-sm"
                >
                  {addingMember ? "Adding…" : "Add"}
                </button>
              </div>
            </div>
          )}

          {/* Members list */}
          <div className="max-h-80 overflow-y-auto space-y-2">
            {loadingMembers ? (
              <p className="caption text-muted text-center py-6">Loading members…</p>
            ) : members.length === 0 ? (
              <p className="caption text-muted text-center py-6">
                No members in this organization yet.
              </p>
            ) : (
              members.map((m) => (
                <div
                  key={m.user_id}
                  className="flex items-center justify-between gap-3 rounded-lg border border-hairline p-3 text-sm"
                >
                  <div className="min-w-0">
                    <span className="font-medium text-ink truncate block">
                      {m.username || m.email || m.user_id}
                    </span>
                    <span className="caption text-muted truncate block">{m.email}</span>
                  </div>

                  <div className="flex items-center gap-2">
                    <span
                      className={`badge-pill text-xs uppercase ${
                        m.role === "manager"
                          ? "bg-brand/10 text-brand border border-brand/20"
                          : ""
                      }`}
                    >
                      {m.role}
                    </span>

                    {canManageTenant && (
                      <>
                        <button
                          type="button"
                          onClick={() => void handleToggleMemberRole(m)}
                          className="btn btn-outline btn-sm text-xs py-1"
                        >
                          {m.role === "manager" ? "Set as Member" : "Make Manager"}
                        </button>
                        <button
                          type="button"
                          onClick={() => void handleRemoveMember(m.user_id)}
                          className="btn btn-ghost btn-sm p-1.5 text-muted hover:text-rose-600"
                          title="Remove from org"
                        >
                          <IconTrash className="h-3.5 w-3.5" />
                        </button>
                      </>
                    )}
                  </div>
                </div>
              ))
            )}
          </div>

          <div className="flex justify-end pt-2">
            <button
              type="button"
              className="btn btn-outline"
              onClick={() => setActiveOrg(null)}
            >
              Close
            </button>
          </div>
        </div>
      </Modal>

      {/* Invite Link Modal */}
      <Modal
        open={inviteOrg !== null}
        title={`Invite Link for ${inviteOrg?.name || "Organization"}`}
        onClose={() => setInviteOrg(null)}
      >
        <div className="space-y-4">
          <p className="caption text-muted">
            Generate a registration link that enrols joiners directly into {inviteOrg?.name}.
          </p>

          <label className="block">
            <span className="caption mb-1.5 block text-muted">Workspace Role</span>
            <Select
              value={inviteRole}
              onChange={(v) => setInviteRole(v as TenantRole)}
              options={[
                { value: "member", label: "Member" },
                { value: "admin", label: "Admin" },
              ]}
            />
          </label>

          <label className="block">
            <span className="caption mb-1.5 block text-muted">Message / Context (optional)</span>
            <input
              type="text"
              placeholder="e.g. Join our data science group"
              className="input"
              value={inviteMsg}
              onChange={(e) => setInviteMsg(e.target.value)}
            />
          </label>

          {inviteUrl ? (
            <div className="rounded-xl border border-hairline bg-surface-strong/50 p-4 space-y-2">
              <span className="caption font-medium text-ink">Organization Invite Link</span>
              <div className="flex items-center gap-2">
                <input
                  type="text"
                  readOnly
                  value={inviteUrl}
                  className="input text-xs font-mono select-all"
                />
                <button
                  type="button"
                  onClick={async () => {
                    const ok = await copyToClipboard(inviteUrl);
                    if (ok) {
                      setLinkCopied(true);
                      setTimeout(() => setLinkCopied(false), 2000);
                    }
                  }}
                  className="btn btn-primary shrink-0 text-xs"
                >
                  {linkCopied ? "Copied!" : "Copy link"}
                </button>
              </div>
            </div>
          ) : (
            <button
              type="button"
              disabled={generatingLink}
              onClick={() => void handleGenerateOrgInvite()}
              className="btn btn-primary w-full"
            >
              {generatingLink ? "Generating…" : "Generate Organization Link"}
            </button>
          )}

          <div className="flex justify-end pt-2">
            <button
              type="button"
              className="btn btn-outline"
              onClick={() => setInviteOrg(null)}
            >
              Close
            </button>
          </div>
        </div>
      </Modal>
    </div>
  );
}

// frontend/src/views/settings/TenantOrgs.vue
<template>
  <div class="tenant-orgs">
    <div class="section-header">
      <div class="section-header-row">
        <div class="section-header-titlewrap">
          <h2>{{ $t('tenantOrg.title') }}</h2>
        </div>
        <t-button v-if="canManageTenant" theme="primary" size="small" @click="openCreateDialog">
          <template #icon><t-icon name="add" /></template>
          {{ $t('tenantOrg.create') }}
        </t-button>
      </div>
      <p class="section-description">{{ $t('tenantOrg.sectionDescription') }}</p>
    </div>

    <t-loading :loading="loading">
      <t-table row-key="id" :data="orgs" :columns="orgColumns" size="medium" hover>
        <template #name="{ row }">
          <div class="org-name-cell">
            <span class="org-name">{{ row.name }}</span>
            <span class="org-member-count">{{ $t('tenantOrg.memberCount', { count: row.member_count || 0 }) }}</span>
          </div>
        </template>
        <template #actions="{ row }">
          <t-button variant="text" size="small" @click="openMembers(row)">
            {{ $t('tenantOrg.members') }}
          </t-button>
          <t-button variant="text" size="small" @click="openInvite(row)">
            {{ $t('tenantOrg.inviteLink') }}
          </t-button>
          <t-button v-if="canManageTenant || managedOrgIds.has(row.id)" variant="text" size="small" @click="openEdit(row)">
            {{ $t('common.edit') }}
          </t-button>
          <t-button v-if="canManageTenant" theme="danger" variant="text" size="small" @click="confirmDelete(row)">
            {{ $t('common.delete') }}
          </t-button>
        </template>
        <template #empty>
          <div class="empty-state">{{ $t('tenantOrg.empty') }}</div>
        </template>
      </t-table>
    </t-loading>

    <!-- Create / edit org -->
    <t-dialog v-model:visible="orgDialog" :header="editingOrg ? $t('tenantOrg.editTitle') : $t('tenantOrg.createTitle')"
      :confirm-btn="{ content: $t('common.confirm'), loading: saving }" :on-confirm="saveOrg"
      :on-close="() => (orgDialog = false)">
      <t-form label-align="top">
        <t-form-item :label="$t('tenantOrg.nameLabel')" required>
          <t-input v-model="orgForm.name" :maxlength="255" :placeholder="$t('tenantOrg.namePlaceholder')" />
        </t-form-item>
        <t-form-item :label="$t('tenantOrg.descriptionLabel')">
          <t-textarea v-model="orgForm.description" :maxlength="1000" :autosize="{ minRows: 2, maxRows: 4 }" />
        </t-form-item>
      </t-form>
    </t-dialog>

    <!-- Members drawer -->
    <t-drawer v-model:visible="membersDrawer" :header="membersTitle" size="480px">
      <div class="members-pane">
        <div class="members-toolbar">
          <t-select v-model="newMemberId" :options="memberCandidates" filterable
            :placeholder="$t('tenantOrg.addMemberPlaceholder')" class="member-select" />
          <t-select v-model="newMemberRole" :options="orgRoleOptions" class="role-select" />
          <t-button theme="primary" size="small" :disabled="!newMemberId" :loading="saving" @click="addMember">
            {{ $t('tenantOrg.addMember') }}
          </t-button>
        </div>
        <t-table row-key="user_id" :data="members" :columns="memberColumns" size="small" hover>
          <template #role="{ row }">
            <t-tag :theme="row.role === 'manager' ? 'primary' : 'default'" variant="light" size="small">
              {{ $t('tenantOrg.role.' + row.role) }}
            </t-tag>
          </template>
          <template #memberActions="{ row }">
            <t-button v-if="row.role === 'member'" variant="text" size="small" @click="promote(row)">
              {{ $t('tenantOrg.makeManager') }}
            </t-button>
            <t-button v-else variant="text" size="small" @click="demote(row)">
              {{ $t('tenantOrg.makeMember') }}
            </t-button>
            <t-button theme="danger" variant="text" size="small" @click="removeMember(row)">
              {{ $t('common.delete') }}
            </t-button>
          </template>
        </t-table>
      </div>
    </t-drawer>

    <!-- Invite link dialog -->
    <t-dialog v-model:visible="inviteDialog" :header="$t('tenantOrg.inviteTitle', { org: activeOrg?.name || '' })"
      :confirm-btn="{ content: $t('tenantOrg.generateLink'), loading: saving }" :on-confirm="generateInvite"
      :on-close="() => (inviteDialog = false)">
      <t-form label-align="top">
        <t-form-item :label="$t('tenantOrg.inviteRole')">
          <t-select v-model="inviteRole" :options="inviteRoleOptions" />
        </t-form-item>
        <t-form-item :label="$t('tenantOrg.inviteMessage')">
          <t-input v-model="inviteMessage" :maxlength="500" />
        </t-form-item>
      </t-form>
      <div v-if="inviteUrl" class="invite-result">
        <t-input :value="inviteUrl" readonly>
          <template #suffix>
            <t-button size="small" variant="text" @click="copyInviteUrl">
              <t-icon name="file-copy" />
            </t-button>
          </template>
        </t-input>
        <p class="invite-hint">{{ $t('tenantOrg.inviteHint') }}</p>
      </div>
    </t-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { MessagePlugin, DialogPlugin } from 'tdesign-vue-next'
import { useAuthStore } from '@/stores/auth'
import { copyWithToast } from '@/utils/clipboard'
import { fetchAllTenantMembers } from '@/api/tenant/members'
import {
  listOrgs, createOrg, updateOrg, deleteOrg,
  listOrgMembers, addOrgMember, updateOrgMemberRole, removeOrgMember,
  createOrgInviteLink,
  type TenantOrg, type TenantOrgMember, type TenantOrgRole,
} from '@/api/tenant/orgs'
import type { TenantRole } from '@/api/tenant/members'

const { t } = useI18n()
const authStore = useAuthStore()

const orgs = ref<TenantOrg[]>([])
const loading = ref(false)
const saving = ref(false)

// Tenant Admin/Owner manage orgs; org managers only see actions the
// backend will accept (member ops + invite links on their own orgs).
const canManageTenant = computed(() => authStore.canAccessAllTenants || authStore.hasRole('admin'))
const managedOrgIds = ref<Set<number>>(new Set())

const orgDialog = ref(false)
const editingOrg = ref<TenantOrg | null>(null)
const orgForm = ref({ name: '', description: '' })

const membersDrawer = ref(false)
const activeOrg = ref<TenantOrg | null>(null)
const members = ref<TenantOrgMember[]>([])
const tenantMembers = ref<Array<{ user_id: string; username: string; email: string }>>([])
const newMemberId = ref('')
const newMemberRole = ref<TenantOrgRole>('member')

const inviteDialog = ref(false)
const inviteRole = ref<TenantRole>('viewer')
const inviteMessage = ref('')
const inviteUrl = ref('')

const membersTitle = computed(() =>
  activeOrg.value ? t('tenantOrg.membersTitle', { org: activeOrg.value.name }) : '')
const memberCandidates = computed(() =>
  tenantMembers.value
    .filter((m) => !members.value.some((om) => om.user_id === m.user_id))
    .map((m) => ({ label: `${m.username} (${m.email})`, value: m.user_id })))
const orgRoleOptions = computed(() => [
  { label: t('tenantOrg.role.member'), value: 'member' },
  { label: t('tenantOrg.role.manager'), value: 'manager' },
])
const inviteRoleOptions = computed(() => [
  { label: t('tenantMember.role.viewer'), value: 'viewer' },
  { label: t('tenantMember.role.contributor'), value: 'contributor' },
])

const orgColumns = computed(() => [
  { colKey: 'name', title: t('tenantOrg.nameLabel'), cell: 'name' },
  { colKey: 'description', title: t('tenantOrg.descriptionLabel'), ellipsis: true },
  { colKey: 'actions', title: t('tenantMember.columns.operations'), cell: 'actions', width: 260 },
])
const memberColumns = computed(() => [
  { colKey: 'username', title: t('tenantMember.columns.member'), ellipsis: true,
    cell: (h: any, { row }: any) => row.username || row.email || row.user_id },
  { colKey: 'role', title: t('tenantOrg.roleLabel'), cell: 'role', width: 100 },
  { colKey: 'memberActions', title: t('tenantMember.columns.operations'), cell: 'memberActions', width: 170 },
])

const loadOrgs = async () => {
  loading.value = true
  try {
    const res: any = await listOrgs()
    orgs.value = res?.data || []
  } catch (e: any) {
    MessagePlugin.error(e?.message || t('tenantOrg.loadFailed'))
  } finally {
    loading.value = false
  }
}

const openCreateDialog = () => {
  editingOrg.value = null
  orgForm.value = { name: '', description: '' }
  orgDialog.value = true
}
const openEdit = (org: TenantOrg) => {
  editingOrg.value = org
  orgForm.value = { name: org.name, description: org.description || '' }
  orgDialog.value = true
}
const saveOrg = async () => {
  if (!orgForm.value.name.trim()) return
  saving.value = true
  try {
    if (editingOrg.value) {
      await updateOrg(editingOrg.value.id, orgForm.value)
    } else {
      await createOrg(orgForm.value)
    }
    orgDialog.value = false
    await loadOrgs()
  } catch (e: any) {
    MessagePlugin.error(e?.message || t('tenantOrg.saveFailed'))
  } finally {
    saving.value = false
  }
}
const confirmDelete = (org: TenantOrg) => {
  const d = DialogPlugin.confirm({
    header: t('common.confirm'),
    body: t('tenantOrg.deleteConfirm', { name: org.name }),
    onConfirm: async () => {
      d.destroy()
      try {
        await deleteOrg(org.id)
        await loadOrgs()
      } catch (e: any) {
        MessagePlugin.error(e?.message || t('tenantOrg.deleteFailed'))
      }
    },
    onCancel: () => d.destroy(),
  })
}

const openMembers = async (org: TenantOrg) => {
  activeOrg.value = org
  membersDrawer.value = true
  newMemberId.value = ''
  const tenantId = Number(authStore.currentTenantId || 0)
  const [mRes, tmRes]: any[] = await Promise.all([
    listOrgMembers(org.id),
    tenantId ? fetchAllTenantMembers(tenantId) : Promise.resolve([]),
  ])
  members.value = mRes?.data || []
  tenantMembers.value = tmRes || []
}
const addMember = async () => {
  if (!activeOrg.value || !newMemberId.value) return
  saving.value = true
  try {
    await addOrgMember(activeOrg.value.id, { user_id: newMemberId.value, role: newMemberRole.value })
    newMemberId.value = ''
    const res: any = await listOrgMembers(activeOrg.value.id)
    members.value = res?.data || []
    await loadOrgs()
  } catch (e: any) {
    MessagePlugin.error(e?.message || t('tenantOrg.saveFailed'))
  } finally {
    saving.value = false
  }
}
const setRole = async (row: TenantOrgMember, role: TenantOrgRole) => {
  if (!activeOrg.value) return
  try {
    await updateOrgMemberRole(activeOrg.value.id, row.user_id, { role })
    const res: any = await listOrgMembers(activeOrg.value.id)
    members.value = res?.data || []
  } catch (e: any) {
    MessagePlugin.error(e?.message || t('tenantOrg.saveFailed'))
  }
}
const promote = (row: TenantOrgMember) => setRole(row, 'manager')
const demote = (row: TenantOrgMember) => setRole(row, 'member')
const removeMember = async (row: TenantOrgMember) => {
  if (!activeOrg.value) return
  try {
    await removeOrgMember(activeOrg.value.id, row.user_id)
    const res: any = await listOrgMembers(activeOrg.value.id)
    members.value = res?.data || []
    await loadOrgs()
  } catch (e: any) {
    MessagePlugin.error(e?.message || t('tenantOrg.saveFailed'))
  }
}

const openInvite = (org: TenantOrg) => {
  activeOrg.value = org
  inviteDialog.value = true
  inviteUrl.value = ''
  inviteMessage.value = ''
}
const generateInvite = async () => {
  if (!activeOrg.value) return
  saving.value = true
  try {
    const res: any = await createOrgInviteLink(activeOrg.value.id, {
      role: inviteRole.value,
      message: inviteMessage.value || undefined,
    })
    inviteUrl.value = res?.data?.url || ''
    if (inviteUrl.value && inviteUrl.value.startsWith('/')) {
      inviteUrl.value = window.location.origin + inviteUrl.value
    }
  } catch (e: any) {
    MessagePlugin.error(e?.message || t('tenantOrg.saveFailed'))
  } finally {
    saving.value = false
  }
}
const copyInviteUrl = () => {
  if (inviteUrl.value) copyWithToast(inviteUrl.value, 'tenantOrg.linkCopied')
}

onMounted(loadOrgs)
</script>

<style scoped lang="less">
.tenant-orgs {
  .section-header {
    margin-bottom: 16px;
  }
  .section-header-row {
    display: flex;
    align-items: center;
    justify-content: space-between;
  }
  .section-description {
    color: var(--td-text-color-secondary);
    font-size: 13px;
    margin-top: 4px;
  }
  .org-name-cell {
    display: flex;
    flex-direction: column;
    gap: 2px;
  }
  .org-name {
    font-weight: 500;
  }
  .org-member-count {
    font-size: 12px;
    color: var(--td-text-color-secondary);
  }
  .empty-state {
    padding: 32px 0;
    text-align: center;
    color: var(--td-text-color-secondary);
  }
}
.members-pane {
  .members-toolbar {
    display: flex;
    gap: 8px;
    margin-bottom: 12px;
    .member-select {
      flex: 1;
    }
    .role-select {
      width: 120px;
    }
  }
}
.invite-result {
  margin-top: 12px;
}
.invite-hint {
  margin-top: 8px;
  font-size: 12px;
  color: var(--td-text-color-secondary);
}
</style>
